@TuringMachine.Backend.Server_HostAddress = http://localhost:5066

//  Variable Section. Modify content when needed
@username = Test_User
@rsaEncryptedPassword = Password
@hashedPassword = E7CF3EF4F17C3999A94F2C6F612E8A888E5B1026878E4E19398B23BD38EC221A
@salt = 0
@licenseKey = 6a2da466-b130-47a0-97eb-6ae467a28623
@access_token = DR4jkn8Vb0SYJZf2kOMaQhMeQFVLWauO
@levelID = 1

//  Run the following testing to create database access
GET {{TuringMachine.Backend.Server_HostAddress}}/api/get-rsa-key/
Accept: application/json
###

POST {{TuringMachine.Backend.Server_HostAddress}}/api/gen-key
Accept: application/json
###

POST {{TuringMachine.Backend.Server_HostAddress}}/api/register?username={{username}}&rsaEncryptedPassword={{rsaEncryptedPassword}}&licenseKey={{licenseKey}}
Accept: application/json
###

POST {{TuringMachine.Backend.Server_HostAddress}}/api/login?username={{username}}&hashedPassword={{hashedPassword}}&salt={{salt}}
Accept: application/json
###

//  Sample use cases
GET {{TuringMachine.Backend.Server_HostAddress}}/api/try-get-response/
Accept: application/json
###

GET {{TuringMachine.Backend.Server_HostAddress}}/api/validate?accessToken={{access_token}}
Accept: application/json
###

GET {{TuringMachine.Backend.Server_HostAddress}}/api/progress?accessToken={{access_token}}
Accept: application/json
###

GET {{TuringMachine.Backend.Server_HostAddress}}/api/get-rsa-key/
Accept: application/json
###

GET {{TuringMachine.Backend.Server_HostAddress}}/api/levels?accessToken={{access_token}}
Accept: application/json
###

GET {{TuringMachine.Backend.Server_HostAddress}}/api/level?accessToken={{access_token}}&levelID={{levelID}}
Accept: application/json
###

POST {{TuringMachine.Backend.Server_HostAddress}}/api/upload?accessToken={{access_token}}
Content-Type: application/json
{
    "tapes": [
        { "type": "Infinite"    , "isInput" : true },
        { "type": "Infinite"    , "isOutput": true },
        { "type": "LeftLimited", "values" : "a"  }
    ],
    "machines": [
    {
        "transitions": [
            {
                "source": 0,
                "target": 1,
                "statements": [
                    { "read": "a", "write": "b", "move":  2 } ,
                    { "read": "_", "write": "b", "move": -1 }
                ],
                "transitionLineSteps": [
                    { "X": 50, "Y": 0 }, 
                    { "X": 0, "Y": 50 }
                ]
            }
        ],
        "heads": [
            { "type": "Read" , "tape": 0, "position":  2 },
            { "type": "ReadWrite", "tape": 0, "position": -1 }
        ],
            "startNode": 0,
            "label": {
                "title": "title of the machine",
                "color": 16777215,
                "boxes": [
                    { "start": { "X": 0, "Y": 0 }, "size": { "X": 20, "Y": 50 }, "color": 16777216 }
                ],
                "texts": [
                    { "position": { "X": 10, "Y": 20 }, "value": "textbox string" }
                ],
                "nodes": [
                    { "label": "q0", "position": { "X": 100, "Y": 200} }, 
                    { "label": "q1", "position": { "X": 150, "Y": 250}, "isFinal": true }
                ]
            }
        }
    ]
}
###

POST {{TuringMachine.Backend.Server_HostAddress}}/api/upload?accessToken={{access_token}}
Content-Type: application/json
{
	"tapes": [
		{ "type": "infinite", "values": "aab", "isInput": true, "isOutput": false },
		{ "type": "infinite", "isInput": false, "isOutput": true },
		{ "type": "infinite", "isInput": false, "isOutput": false }
	],
	"machines": [
		{
			"transitions": [
				{
					"source": 0,
					"target": 2,
					"statements": [
						{ "read": "a", "write": "a", "move": 0 },
						{ "read": "/", "write": "_", "move": 0 }
					],
					"transitionLineSteps": [
						{ "x": 0, "y": -115.75178997613364 },
						{ "x": 360.3818615751783, "y": 0 }
					]
				},
				{
					"source": 0,
					"target": 2,
					"statements": [
						{ "read": "b", "write": "b", "move": 0 },
						{ "read": "/", "write": "_", "move": 0 }
					],
					"transitionLineSteps": [
						{ "x": 0, "y": -115.75178997613364 },
						{ "x": 360.3818615751783, "y": 0 }
					]
				},
				{
					"source": 0,
					"target": 2,
					"statements": [
						{ "read": "_", "write": "_", "move": 0 },
						{ "read": "/", "write": "_", "move": 0 }
					],
					"transitionLineSteps": [
						{ "x": 0, "y": -115.75178997613364 },
						{ "x": 360.3818615751783, "y": 0 }
					]
				},
				{
					"source": 2,
					"target": 4,
					"statements": [
						{ "read": "_", "write": "_", "move": 0 },
						{ "read": "/", "write": "_", "move": 1 }
					],
					"transitionLineSteps": [
						{ "x": 0, "y": 189.73747016706443 },
						{ "x": 377.0883054892601, "y": 0 }
					]
				},
				{
					"source": 2,
					"target": 2,
					"statements": [
						{ "read": "a", "write": "_", "move": 1 },
						{ "read": "/", "write": "a", "move": -1 }
					],
					"transitionLineSteps": [
						{ "x": 368.73508353221945, "y": 0 },
						{ "x": 0, "y": -262.5298329355608 },
						{ "x": -368.73508353221945, "y": 0 },
						{ "x": 0, "y": 262.5298329355608 }
					]
				},
				{
					"source": 2,
					"target": 2,
					"statements": [
						{
							"read": "b",
							"write": "_",
							"move": 1
						},
						{
							"read": "/",
							"write": "b",
							"move": -1
						}
					],
					"transitionLineSteps": [
						{ "x": 368.73508353221945, "y": 0 },
						{ "x": 0, "y": -262.5298329355608 },
						{ "x": -368.73508353221945, "y": 0 },
						{ "x": 0, "y": 262.5298329355608 }
					]
				}
			],
			"heads": [
				{
					"type": "ReadWrite",
					"tape": 0,
					"position": 0
				},
				{
					"type": "Write",
					"tape": 1,
					"position": 0
				}
			],
			"startNode": 0,
			"label": {
				"color": 3351585,
				"boxes": [
					{
						"start": { "x": 63, "y": -136 },
						"size": { "x": 96, "y": 99 },
						"color": 10783844
					},
					{},
					{
						"start": { "x": 282, "y": -133 },
						"size": { "x": 90, "y": 100 },
						"color": 13876984
					},
					{},
					{
						"start": { "x": 235, "y": -10 },
						"size": { "x": 83, "y": 85 },
						"color": 5829724
					}
				],
				"texts": [
					{
						"position": { "x": 613, "y": 11 },
						"value": "a"
					},
					{
						"position": { "x": 632, "y": 39 },
						"value": "b"
					},
					{},
					{
						"position": { "x": 674, "y": 38 },
						"value": "d"
					},
					{
						"position": { "x": 702, "y": 12 },
						"value": "e"
					}
				],
				"nodes": [
					{
						"position": { "x": 114.70239302072802, "y": 260.4282377869705 },
						"isFinal": false
					},
					{},
					{
						"position": { "x": 475.084254595907, "y": 144.67644781083686 },
						"isFinal": false
					},
					{},
					{
						"position": { "x": 852.1725600851671, "y": 334.4139179779013 },
						"isFinal": false
					}
				]
			}
		},
		{
			"transitions": [],
			"heads": [],
			"startNode": 0,
			"label": {
				"color": 13185241,
				"boxes": [],
				"texts": [],
				"nodes": [
					{
						"position": { "x": 100, "y": 100 }
					}
				]
			}
		}
	]
}
###

@designID = d3eb906e-3657-4ba5-a88a-9a4915b96c51
GET {{TuringMachine.Backend.Server_HostAddress}}/api/import?accessToken={{access_token}}&designID={{designID}}
Accept: application/json
###

POST  {{TuringMachine.Backend.Server_HostAddress}}/api/register?username=frontend-test-1&rsaEncryptedPassword=D0iq4lxFM7CFa7u0aZMeqAxdhh3qdkOxo0Ndk6LopSZ%2F%2F7gUr%2B5tJCfy%2FBrw8%2FxnIIod3zm38OI1HZqaF9Sj9rNn6g6x2R2lraIY6ZVbkqHQniZrl6Lxkb5q49VE2%2Fisi1zYHRXxwg2z%2BxbPAf57gl%2F2AffqmJuLea7OfuKtEMA8vgSJOoek9%2BIx%2F0w7DuaYVavlHCliPh%2BzhVAO3loDwERbN5LZZw2puKnI2Gzivb4ofQuu%2FB6xpg1tmkTUtPmQP%2BS9e0Cte7wJyFL7wELvDI3oN2PpPkU4RTta6Eqg7uoFKA36xrRINWu2k91HGCaRKjgg5AACGm%2FHtfDzFdFcTQ%3D%3D&licenseKey=eb5e6b80-4a5b-4c95-9a28-265fac159181